### ISSUE TITLE
ERROR: Game halts

### ISSUE THREAD

**Issue by pe1mew** [sciuro/nfgame#1]
When multiple players are playing (>3) and are rapidly scanning cards, the game halts. After multiple "ctrl-C" in the console the game continues and players receive their scan answers from the server. It is independant from type of phone or browser. When the server ie periodically queried by the central pc to show scores the effect is intensified.

**Comment by sciuro** [comment]
Added a front webserver with an wsgi interface. (twisted) Webserver is now multithreaded.
