### ISSUE TITLE
Program won't start

### ISSUE THREAD

**Issue by pe1mew** [sciuro/nfgame#13]
Normal start does not work:

pi@raspberrypi:~/nfgame $ ./run.sh start
./run.sh: line 32: twistd: command not found
Game is started!
Have fun!

http@5000 is not reachable.

using debug is OK

pi@raspberrypi:~/nfgame $ ./run.sh start debug
 * Serving Flask app "nfgame"
 * Forcing debug mode on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 127-574-756

**Comment by sciuro** [comment]
You forgot to install twisted. Please install twisted.
