### ISSUE TITLE
Feature: Start of game only at specific cards.

### ISSUE THREAD

**Issue by pe1mew** [sciuro/nfgame#4]
Allow the use of specific cards where the player can register only. This can be administered in the config file.
When a non registration card is scanned for the first time the player is informed to go to a specific place to register. When a registration card is scanned registration is allowed and time tracking starts

**Comment by sciuro** [comment]
In the config file it's now possible to add a hash to the newuser URL. So it's possible to make a separate QR/NFC tag to register a new user.
